return {
	config=
	{
		[1]=
		{
			id = 1,
			game_type = "game_DdzFree",
			game_name = "新手场",
			game_id = 1,
			order = 1,
			imageIndex = 1,
			base = 300,
			enterMin = 3000,
			enterMax = 20000,
			min_coin = 3000,
			max_coin = 20000,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_jdddz",
			isOnOff = 1,
			isLock = 0,
			 tag_image = "pp_icon_huob",
			max_rate = 24,
		},
		[2]=
		{
			id = 2,
			game_type = "game_DdzFree",
			game_name = "三星场",
			game_id = 2,
			order = 2,
			imageIndex = 2,
			base = 2000,
			enterMin = 20000,
			enterMax = -1,
			min_coin = 20000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 2,
			image = "hall_imgf_jdddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 48,
		},
		[3]=
		{
			id = 3,
			game_type = "game_DdzFree",
			game_name = "四星场",
			game_id = 3,
			order = 3,
			imageIndex = 3,
			base = 5000,
			enterMin = 400000,
			enterMax = -1,
			min_coin = 400000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 3,
			image = "hall_imgf_jdddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 96,
		},
		[4]=
		{
			id = 4,
			game_type = "game_DdzFree",
			game_name = "五星场",
			game_id = 4,
			order = 4,
			imageIndex = 4,
			base = 20000,
			enterMin = 1000000,
			enterMax = -1,
			min_coin = 1000000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 4,
			image = "hall_imgf_jdddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 96,
		},
		[5]=
		{
			id = 5,
			game_type = "game_DdzFreeER",
			game_name = "新手场",
			game_id = 5,
			order = 1,
			imageIndex = 1,
			base = 300,
			enterMin = 5000,
			enterMax = 50000,
			min_coin = 5000,
			max_coin = 50000,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_erddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 20,
		},
		[6]=
		{
			id = 6,
			game_type = "game_DdzFreeER",
			game_name = "三星场",
			game_id = 6,
			order = 2,
			imageIndex = 2,
			base = 2000,
			enterMin = 50000,
			enterMax = -1,
			min_coin = 50000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 2,
			image = "hall_imgf_erddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 40,
		},
		[7]=
		{
			id = 7,
			game_type = "game_DdzFreeER",
			game_name = "四星场",
			game_id = 7,
			order = 3,
			imageIndex = 3,
			base = 10000,
			enterMin = 500000,
			enterMax = -1,
			min_coin = 500000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 3,
			image = "hall_imgf_erddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 80,
		},
		[8]=
		{
			id = 8,
			game_type = "game_DdzFreeER",
			game_name = "五星场",
			game_id = 8,
			order = 4,
			imageIndex = 4,
			base = 30000,
			enterMin = 2000000,
			enterMax = -1,
			min_coin = 2000000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 4,
			image = "hall_imgf_erddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 80,
		},
		[9]=
		{
			id = 9,
			game_type = "game_DdzLaizi",
			game_name = "新手场",
			game_id = 9,
			order = 1,
			imageIndex = 1,
			base = 200,
			enterMin = 10000,
			enterMax = -1,
			min_coin = 10000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_lz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 48,
		},
		[10]=
		{
			id = 10,
			game_type = "game_DdzLaizi",
			game_name = "三星场",
			game_id = 10,
			order = 2,
			imageIndex = 2,
			base = 1000,
			enterMin = 100000,
			enterMax = -1,
			min_coin = 100000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 2,
			image = "hall_imgf_lz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 96,
		},
		[11]=
		{
			id = 11,
			game_type = "game_DdzLaizi",
			game_name = "四星场",
			game_id = 11,
			order = 3,
			imageIndex = 3,
			base = 5000,
			enterMin = 1000000,
			enterMax = -1,
			min_coin = 1000000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 3,
			image = "hall_imgf_lz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 192,
		},
		[12]=
		{
			id = 12,
			game_type = "game_DdzLaizi",
			game_name = "五星场",
			game_id = 12,
			order = 4,
			imageIndex = 4,
			base = 20000,
			enterMin = 5000000,
			enterMax = -1,
			min_coin = 5000000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 4,
			image = "hall_imgf_lz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 192,
		},
		[13]=
		{
			id = 13,
			game_type = "game_MjXzER3D",
			game_name = "新手场",
			game_id = 13,
			order = 1,
			imageIndex = 1,
			base = 1000,
			enterMin = 10000,
			enterMax = -1,
			min_coin = 10000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_ermj",
			isOnOff = 1,
			isLock = 0,
			max_rate = 16,
		},
		[14]=
		{
			id = 14,
			game_type = "game_MjXzER3D",
			game_name = "三星场",
			game_id = 14,
			order = 2,
			imageIndex = 2,
			base = 3000,
			enterMin = 100000,
			enterMax = -1,
			min_coin = 100000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 2,
			image = "hall_imgf_ermj",
			isOnOff = 1,
			isLock = 0,
			max_rate = 32,
		},
		[15]=
		{
			id = 15,
			game_type = "game_MjXzER3D",
			game_name = "四星场",
			game_id = 15,
			order = 3,
			imageIndex = 3,
			base = 10000,
			enterMin = 500000,
			enterMax = -1,
			min_coin = 500000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 3,
			image = "hall_imgf_ermj",
			isOnOff = 1,
			isLock = 0,
			max_rate = 64,
		},
		[16]=
		{
			id = 16,
			game_type = "game_MjXzER3D",
			game_name = "五星场",
			game_id = 16,
			order = 4,
			imageIndex = 4,
			base = 50000,
			enterMin = 2000000,
			enterMax = -1,
			min_coin = 2000000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 4,
			image = "hall_imgf_ermj",
			isOnOff = 1,
			isLock = 0,
			max_rate = 64,
		},
		[17]=
		{
			id = 17,
			game_type = "game_Mj3D",
			game_name = "新手场",
			game_id = 17,
			order = 1,
			imageIndex = 1,
			base = 500,
			enterMin = 3000,
			enterMax = 20000,
			min_coin = 3000,
			max_coin = 20000,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_xz",
			isOnOff = 1,
			isLock = 0,
			 tag_image = "pp_icon_huob",
			play_type = "换三张",
			max_rate = 16,
		},
		[18]=
		{
			id = 18,
			game_type = "game_Mj3D",
			game_name = "三星场",
			game_id = 18,
			order = 2,
			imageIndex = 2,
			base = 2500,
			enterMin = 20000,
			enterMax = -1,
			min_coin = 20000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 2,
			image = "hall_imgf_xz",
			isOnOff = 1,
			isLock = 0,
			play_type = "换三张",
			max_rate = 32,
		},
		[19]=
		{
			id = 19,
			game_type = "game_Mj3D",
			game_name = "四星场",
			game_id = 19,
			order = 3,
			imageIndex = 3,
			base = 7500,
			enterMin = 400000,
			enterMax = -1,
			min_coin = 400000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 3,
			image = "hall_imgf_xz",
			isOnOff = 1,
			isLock = 0,
			play_type = "换三张",
			max_rate = 64,
		},
		[20]=
		{
			id = 20,
			game_type = "game_Mj3D",
			game_name = "五星场",
			game_id = 20,
			order = 4,
			imageIndex = 4,
			base = 25000,
			enterMin = 1000000,
			enterMax = -1,
			min_coin = 1000000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 4,
			image = "hall_imgf_xz",
			isOnOff = 1,
			isLock = 0,
			play_type = "换三张",
			max_rate = 64,
		},
		[21]=
		{
			id = 21,
			game_type = "game_DdzFreeTF",
			game_name = "新手场",
			game_id = 21,
			order = 1,
			imageIndex = 1,
			base = 200,
			enterMin = 3000,
			enterMax = 50000,
			min_coin = 3000,
			max_coin = 50000,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_tfddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 32,
		},
		[22]=
		{
			id = 22,
			game_type = "game_DdzFreeTF",
			game_name = "三星场",
			game_id = 22,
			order = 2,
			imageIndex = 2,
			base = 1000,
			enterMin = 50000,
			enterMax = -1,
			min_coin = 50000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 2,
			image = "hall_imgf_tfddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 64,
		},
		[23]=
		{
			id = 23,
			game_type = "game_DdzFreeTF",
			game_name = "四星场",
			game_id = 23,
			order = 3,
			imageIndex = 3,
			base = 5000,
			enterMin = 500000,
			enterMax = -1,
			min_coin = 500000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 3,
			image = "hall_imgf_tfddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 128,
		},
		[24]=
		{
			id = 24,
			game_type = "game_DdzFreeTF",
			game_name = "五星场",
			game_id = 24,
			order = 4,
			imageIndex = 4,
			base = 20000,
			enterMin = 2000000,
			enterMax = -1,
			min_coin = 2000000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 4,
			image = "hall_imgf_tfddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 128,
		},
		[25]=
		{
			id = 25,
			game_type = "game_Gobang",
			game_name = "五子棋",
			game_id = 25,
			order = 1,
			imageIndex = 1,
			base = 3000,
			enterMin = 3400,
			enterMax = -1,
			min_coin = 3400,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_wzq",
			isOnOff = 1,
			isLock = 0,
			max_rate = 1,
		},
		[26]=
		{
			id = 26,
			game_type = "game_MjXl3D",
			game_name = "血流",
			game_id = 29,
			order = 1,
			imageIndex = 1,
			base = 3000,
			enterMin = 5000,
			enterMax = -1,
			min_coin = 5000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_xl",
			isOnOff = 1,
			isLock = 0,
			max_rate = 32,
		},
	},
}