return {
	config=
	{
		[1]=
		{
			id = 1,
			ID = 1,
			noCloseUI = 0,
			order = 5,
			type = "activity",
			title = "打比赛赢红包！",
			showType = "image",
			parmData = "ad_1",
			gotoUI = "match_hall",
			beginTime = -1,
			endTime = -1,
			isOnOff = 1,
		},
		[2]=
		{
			id = 2,
			ID = 2,
			noCloseUI = 0,
			order = 3,
			type = "activity",
			title = "双11礼物独宠一人！",
			showType = "image",
			parmData = "ad_7",
			tag = "new",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
		[3]=
		{
			id = 3,
			ID = 3,
			noCloseUI = 0,
			order = 1,
			type = "notice",
			title = "不删号内测公告",
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n\n【鲸鱼斗地主】在9月15日（周六）上午10:00开启不删档内测，安卓和IOS版本同步上线！\n登录【鲸鱼斗地主】即赠送1元红包券+6000鲸币+10张房卡+1天记牌器！如遇到任何问题或建议在【鲸鱼斗地主】公众号反馈即可。\n\n温馨提示：因苹果商店政策原因，苹果用户钻石充值比例为1:66（公众号充值比例1:100），请用苹果手机的玩家在官方公众号【鲸鱼斗地主】进行充值。充值方法：点击个人中心→充值中心。\n\n                                                                     《鲸鱼斗地主》运营团队\n                                                                                2018年9月15日",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
			isOnOff = 1,
		},
		[4]=
		{
			id = 4,
			ID = 4,
			noCloseUI = 0,
			order = 0,
			type = "activity",
			title = "鲸鱼杯大奖赛",
			showType = "image",
			parmData = "ad_5",
			gotoUI = "citymatch_hall",
			tag = "hot",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
		[5]=
		{
			id = 5,
			ID = 5,
			noCloseUI = 1,
			order = 6,
			type = "activity",
			title = "2元超值礼包",
			showType = "image",
			parmData = "ad_4",
			gotoUI = "2_gift_bag",
			tag = "hot",
			beginTime = -1,
			endTime = -1,
			isOnOff = 1,
		},
		[6]=
		{
			id = 6,
			ID = 6,
			noCloseUI = 0,
			order = 4,
			type = "notice",
			title = "官方微信群",
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n\n鲸鱼斗地主官方微信群正式上线啦，请添加客服微信号：jyddz01或jyddz02，由客服拉您进群，群里不定时红包雨，还有漂亮的小姐姐小哥哥可以聊天哦，期待您的加入！\n感谢您对鲸鱼斗地主的热爱和支持！\n\n                                                                     鲸鱼斗地主运营团队敬上\n                                                                                2018年10月12日",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
			isOnOff = 1,
		},
		[7]=
		{
			id = 7,
			ID = 7,
			noCloseUI = 0,
			order = 4,
			type = "activity",
			title = "现金奖池来袭！",
			showType = "image",
			gotoUI = "free_hall",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
		[8]=
		{
			id = 8,
			ID = 8,
			noCloseUI = 0,
			order = 2,
			type = "activity",
			title = "房卡场免费啦！",
			showType = "image",
			parmData = "ad_8",
			gotoUI = "roomcard_hall",
			tag = "hot",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
		[9]=
		{
			id = 9,
			ID = 9,
			noCloseUI = 0,
			order = 1,
			type = "activity",
			title = "合伙人礼包",
			showType = "image",
			parmData = "ad_9",
			gotoUI = "hall_tgr",
			tag = "hot",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
		[10]=
		{
			id = 10,
			ID = 10,
			noCloseUI = 0,
			order = 3,
			type = "notice",
			title = "兑奖公告",
			showType = "notice",
			parmData = "兑换商城温馨提示：\n\n1.红包劵是平台回馈给玩家的一种免费获得的累积型兑换券，可以在兑换商城中兑换话费或者实物；红包券可以通过完成牌局任务，参加公益锦标赛赢取，不能通过充值、玩家之间的转让获得；\n\n2.利用BUG等不正当手段获取的红包券，一经查实，红包券将清零及禁止兑换处理；\n\n3.为了更好的向玩家提供服务，兑换商城将会对不同的玩家ID推送不同的礼品内容；\n\n4.为了进行合理的风险控制以及客观情况的要求，兑换存在库存、区域、以及每日兑换频率等限制；\n\n5.根据运营以及供货方的货源情况，我们将不定期上架或者下架礼品内容；\n\n6.竟娱互动保留最终解释权。",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
			isOnOff = 1,
		},
		[11]=
		{
			id = 11,
			ID = 11,
			noCloseUI = 0,
			order = 2,
			type = "notice",
			title = "重要公告",
			showType = "notice",
			parmData = "重要公告：\n\n本平台倡导绿色休闲游戏，游戏中的鲸币为道具，不具有任何的实际货币价值，只限于玩家在游戏中使用。同时，本平台对玩家的鲸币不提供任何形式的官方回购、直接或间接兑换现金、兑换实物、相互转赠、转让等服务。\n\n在此，本平台明令禁止玩家之间任何形式的鲸币交易，鲸币转让等行为，坚决抵制低俗、不健康或涉及赌博等违法违规行为，以及其他违背游戏公平的作弊行为，一经核实，将被处以禁止登陆游戏、删除游戏数据等处罚。",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
			isOnOff = 1,
		},
	},
}