--
-- Author: lyx
-- Date: 2018/3/10
-- Time: 15:07
-- 说明：测试
-- 使用方法：
--  call <service addr> exe_file "hotfix/fixtest.lua"
--

local skynet = require "skynet_plus"
local cluster = require "skynet.cluster"
local base = require "base"
local nodefunc = require "nodefunc"
local basefunc = require "basefunc"
require "normal_enum"


require "printfunc"

local DATA = base.DATA
local CMD = base.CMD
local PUBLIC=base.PUBLIC


local rank_list_test=
{
   {
      player_name="放松一下",
      score="8591",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eqkeBU8Uo4VdLDAMvOq0g7mibmOsibnPXeIvu7a6LyIzpJG02uy0IulbkG4CYWEicl9ickNicsSSGH1cEA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102330671",
      hide_score="70",
      revive_num="0",
      match_model="naming_qys",
      rank=1,
    },
   {
      player_name="死性不改",
      score="5590",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/8CovDCfQxP1ygT3ydK24ibMVZLibTa7mZUb5AhR5qTv7rFAJiaJibPydlhicwZB4xdtBDpKEMKemr18t2MibibCEic18Yw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102454624",
      hide_score="44",
      revive_num="0",
      match_model="naming_qys",
      rank=2,
    },
   {
      player_name="小肉",
      score="4609",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epBw2m0OMhte7Nd6rYCDsMdxkVS1BH1uG5zmrTvpPQ1Dnj6z6v2PvyJsBde1FU1zUE6xbdSQyjhbA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102784050",
      hide_score="60",
      revive_num="0",
      match_model="naming_qys",
      rank=3,
    },
   {
      player_name="一抹时光",
      score="5603",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/gcqD8XSIafbeMJPpjJWrqfQfjgrRq5rD8hzUhzwGfjvz5iaLTne1bn7wyMeSOY86nk2InX4jydC5ow0QjxI3pcw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102596929",
      hide_score="53",
      revive_num="0",
      match_model="naming_qys",
      rank=4,
    },
   {
      player_name="青山黄土头ec",
      score="5057",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_6060.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6856",
      hide_score="40",
      revive_num="0",
      match_model="naming_qys",
      rank=5,
    },
   {
      player_name="吥輕易說倣掱",
      score="5012",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl4619.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6875",
      hide_score="32",
      revive_num="0",
      match_model="naming_qys",
      rank=6,
    },
   {
      player_name="自闭症患者",
      score="4669",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_7494.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6972",
      hide_score="41",
      revive_num="0",
      match_model="naming_qys",
      rank=7,
    },
   {
      player_name="1",
      score="4372",
      head_link="",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102589046",
      hide_score="49",
      revive_num="1",
      match_model="naming_qys",
      rank=8,
    },
   {
      player_name="🍉",
      score="3458",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/ibXIgvpLnpZH1FGHkSPQ5SJbOia7cf6OLRSBpNvSUwPpEbRIbWej5zZYCqqqQiaoTPkphpQQ7wJCEXJfhkFwNuHAQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="10884335",
      hide_score="55",
      revive_num="0",
      match_model="naming_qys",
      rank=9,
    },
    {
      player_name="迷一样的男孩",
      score="4084",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/htmIicoZOenDPL1cz4Yr5j6mm6e023uqPibicawFia0S0siaMUGhp6qD60kliaW4p06d4SIhHvXiaFdWPt3wOqVGHDYmw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102133398",
      hide_score="39",
      revive_num="0",
      match_model="naming_qys",
      rank=10,
    },
    {
      player_name="逆风",
      score="4064",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/OSEHAaamHiajuxhpicj3R9icBpO65hX0zu8or1dRTd6qzMZH4rPyHNLcs21GphWSatt9YWAKzgRWT46AW0SSsoeibw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102880870",
      hide_score="50",
      revive_num="0",
      match_model="naming_qys",
      rank=11,
    },
    {
      player_name="🍓",
      score="4062",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJTOuGuPUvah9v2vyjYfnQia0znr1blIR03ibj9Ticcia5S0a89aytBPBuWGqfr76pbfOA2oQC6EgibUZQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102820338",
      hide_score="52",
      revive_num="0",
      match_model="naming_qys",
      rank=12,
    },
    {
      player_name="࿂Ꮆrc࿐",
      score="4054",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/WKRNrNm8iaBQ9c2kicZBHWicEtfKhiceJuqEcJgYzVic6cZ1xk6QvqPcSDSM3hYqAuHiaNNErb0dmoyKzyfibTWyKTX7w/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102870214",
      hide_score="57",
      revive_num="0",
      match_model="naming_qys",
      rank=13,
    },
    {
      player_name="淡若～云~烟",
      score="3756",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJNTPGbBgL8gOfn3FrlmtqeOdQotm6XkDdseianQV8WPXl1J99hiaA3oLYOFL9nzwgUMRMvfAj8ichHw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102493560",
      hide_score="51",
      revive_num="0",
      match_model="naming_qys",
      rank=14,
    },
    {
      player_name="条鱼",
      score="3273",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl2335.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6769",
      hide_score="26",
      revive_num="0",
      match_model="naming_qys",
      rank=15,
    },
    {
      player_name="阿难",
      score="3257",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTIiazrX0QfcGlZzia87q2X6Qx1YKLxyHM4zf9XZ1wZa3XsWmgXgrKHGzQNkib00nIXTicZH4UvPCY7WGA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102748427",
      hide_score="56",
      revive_num="0",
      match_model="naming_qys",
      rank=16,
    },
    {
      player_name="陆枫",
      score="2939",
      head_link="",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102777151",
      hide_score="63",
      revive_num="0",
      match_model="naming_qys",
      rank=17,
    },
    {
      player_name="伴风望海",
      score="2870",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_1860.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6896",
      hide_score="35",
      revive_num="0",
      match_model="naming_qys",
      rank=18,
    },
    {
      player_name="碎花裙",
      score="2442",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl1411.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6821",
      hide_score="39",
      revive_num="0",
      match_model="naming_qys",
      rank=19,
    },
    {
      player_name="松松",
      score="2323",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eosHyW7quZ9IcdNiaepTRXKMAhb0kcEgiaZFjWAlwSzeXReKNzl7f9cdQB6FrAricNwAWI4dt9WR2H6w/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102763657",
      hide_score="46",
      revive_num="0",
      match_model="naming_qys",
      rank=20,
    },
    {
      player_name="燕",
      score="1615",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83erdUQuedXfTOImMkSTWKicXGj7kA6ll8Od6wiaftsdrJPLicnITIFWV7o6P5m9CN0OHrdLVrgw1MnBMA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102073291",
      hide_score="48",
      revive_num="0",
      match_model="naming_qys",
      rank=21,
    },
    {
      player_name="1154",
      score="2377",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/qIQhvlIuAnia2KSdT75hmFcQAl7SMib9I6DvbK0m5WtluicXmUTH4CNsblGicBUCZshxVXBX7sGrJ45zrQ0YbaX1WA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102585733",
      hide_score="21",
      revive_num="0",
      match_model="naming_qys",
      rank=22,
    },
    {
      player_name="梦的远方",
      score="2371",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_4349.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6941",
      hide_score="34",
      revive_num="0",
      match_model="naming_qys",
      rank=23,
    },
    {
      player_name="吕大叔",
      score="2364",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/v0ISZWeWN1XRBvA8e7DujEQoWfIZE1oYx00qX1cEKVRfcJficYoutXvTaPLNn68UJq89WicshqEz25caXWCnNDDg/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102900410",
      hide_score="34",
      revive_num="0",
      match_model="naming_qys",
      rank=24,
    },
    {
      player_name="空谷幽蓝",
      score="2283",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTIfanFzmAMw8As3gjcaOUNkzjDDUylybhYwAeK6mXnUnngibCzDWKucqkccqwicTfdSYnqibPgsKib4wg/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102884011",
      hide_score="30",
      revive_num="0",
      match_model="naming_qys",
      rank=25,
    },
    {
      player_name="城南诗客",
      score="1969",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_5679.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_7005",
      hide_score="40",
      revive_num="0",
      match_model="naming_qys",
      rank=26,
    },
    {
      player_name="森目",
      score="1617",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Umq9AKuIOWpgDQicuZGia9rEtIxKPGE2T81HNrMOEHox5ib5Nd06hXficKicFnC3ZEFx5DicVMtCIUF8tyCuqcaIq3JA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102869419",
      hide_score="44",
      revive_num="0",
      match_model="naming_qys",
      rank=27,
    },
    {
      player_name="西红柿鸡蛋汤",
      score="1259",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLpeS1CbNkusEsSzUicxsXw5bBywoKyRTG5TAGHKMuhOjtPyT5Ey4d0SZf0ZzdiazJV5bEJeia8rR8og/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102864484",
      hide_score="38",
      revive_num="0",
      match_model="naming_qys",
      rank=28,
    },
    {
      player_name="訫",
      score="1131",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/PosD56JkdHicvC5Gj591wsw1QADicVwFw8wQMxMQicAujg2picvcb3LmtbjmBUcOiaNCTWicQ9xy4zaJFuDrCiaoTBCdA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102899824",
      hide_score="20",
      revive_num="0",
      match_model="naming_qys",
      rank=29,
    },
    {
      player_name="会痛的心",
      score="982",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/mzZkwf53jx1ibafOjJnCH5LuibtjUDPfVj1cZRWKMBmV7SDQOFezYicKZuwxGDULo8dm9N1LmlJy8HTqDf14c50ow/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102902793",
      hide_score="42",
      revive_num="1",
      match_model="naming_qys",
      rank=30,
    },
    {
      player_name="以你为瘾",
      score="880",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_5855.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6911",
      hide_score="13",
      revive_num="0",
      match_model="naming_qys",
      rank=31,
    },
    {
      player_name=".",
      score="868",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/TWcTJDwjRQhMYTnnBn8EXcfvkORbOiaOUM0cSaFicvfwYmjQ38YAe9jFQY1gicx2ibD0dSia1NPerTuibd1icghyfiak5w/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102867229",
      hide_score="47",
      revive_num="0",
      match_model="naming_qys",
      rank=32,
    },
    {
      player_name="看什么电视",
      score="787",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/CZ2b2tmkqp9LxaQ8LwZzruvQd9nn9rAfAddKV7XBMECR3ibxwJoBzImt4m3ibtw8d3MSu0xlNjKOL88503hliaBDg/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102856917",
      hide_score="29",
      revive_num="0",
      match_model="naming_qys",
      rank=33,
    },
    {
      player_name="旧事。",
      score="694",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTIBzYnG5egxLrjdLWVmwjx4ic2lv8micLnMblG3vgXT03Jxv4Wwpybq3NhmnyTxjfCH54rI79KlkLgQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102725288",
      hide_score="35",
      revive_num="0",
      match_model="naming_qys",
      rank=34,
    },
    {
      player_name="จุ๊บ永恒成为现实",
      score="615",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/6S1dibmGAUia1D3yCiatLCaBQHuoEmC16AZnicThXeDjJjcwuqBibBwLhhRJR5picJj6fWvicaX7WBX73BAo60MbQHebg/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="101845505",
      hide_score="42",
      revive_num="0",
      match_model="naming_qys",
      rank=35,
    },
    {
      player_name="小女巫卢娜",
      score="483",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl1295.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6925",
      hide_score="28",
      revive_num="0",
      match_model="naming_qys",
      rank=36,
    },
    {
      player_name="老林",
      score="264",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/cKdqUDGrCBibMzS3Tew56JFq2vWD7dmCI3ZvXWiakgTiczct0dTeAgQP7JsMtJl46dVpiaWicwWnoBeIribUfhjkAGZA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102736080",
      hide_score="24",
      revive_num="1",
      match_model="naming_qys",
      rank=37,
    },
    {
      player_name="麦大麦",
      score="-145",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl1298.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6932",
      hide_score="28",
      revive_num="0",
      match_model="naming_qys",
      rank=38,
    },
    {
      player_name="魔",
      score="-945",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/UvcgRMqsTJIpicqjrdm0qlYuCtEJg2TvBzTYw7nX8wxTmhxanAWk64hWmeIj75EEibXfb8ZXgnwHXRWgQbsweiaCw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102889215",
      hide_score="41",
      revive_num="0",
      match_model="naming_qys",
      rank=39,
    },
    {
      player_name="拾忆",
      score="1277",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl1475.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6843",
      hide_score="28",
      revive_num="0",
      match_model="naming_qys",
      rank=40,
    },
    {
      player_name="李健",
      score="1267",
      head_link="",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102782600",
      hide_score="38",
      revive_num="0",
      match_model="naming_qys",
      rank=41,
    },
    {
      player_name="简单就好",
      score="1206",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eoRvticNGIibVJjcjXZXNdRJhWGZiciaX7zS46t71H4NCxSoJ2OZ75gjw3kVOsFzG2G7E8LpSlReP5KicQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102832614",
      hide_score="26",
      revive_num="1",
      match_model="naming_qys",
      rank=42,
    },
    {
      player_name="碳酸控怪叔叔",
      score="1204",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_8194.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6999",
      hide_score="23",
      revive_num="0",
      match_model="naming_qys",
      rank=43,
    },
    {
      player_name="我们的爱呀",
      score="1179",
      head_link="",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102885660",
      hide_score="32",
      revive_num="0",
      match_model="naming_qys",
      rank=44,
    },
    {
      player_name="爱，,,这生活",
      score="1172",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl6173.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6798",
      hide_score="39",
      revive_num="0",
      match_model="naming_qys",
      rank=45,
    },
    {
      player_name="清浅旧时光",
      score="1073",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl4704.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6986",
      hide_score="31",
      revive_num="0",
      match_model="naming_qys",
      rank=46,
    },
    {
      player_name="邵小咪",
      score="909",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eoXibk4hrcibozicnEraia8QOhsOSSZan1x3BZaB0icQnLtf5ejRprjNYLK238xviaP6cKwV537duTLiaIvA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102200240",
      hide_score="36",
      revive_num="0",
      match_model="naming_qys",
      rank=47,
    },
    {
      player_name="砖家讲座",
      score="887",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_5205.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6787",
      hide_score="16",
      revive_num="0",
      match_model="naming_qys",
      rank=48,
    },
    {
      player_name="玉",
      score="855",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/9iaIh7dicWC24AW73ubcNuScJ3m7oKu922c3gIu5wj6OYDoBxdVMwOl1Ew73cpEPt5ib8bRcVpJFpXEAMnVjDxvNg/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="1082645",
      hide_score="31",
      revive_num="0",
      match_model="naming_qys",
      rank=49,
    },
    {
      player_name="欧辰-夏沫",
      score="855",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl1059.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6806",
      hide_score="14",
      revive_num="0",
      match_model="naming_qys",
      rank=50,
    },
    {
      player_name="温澜潮生",
      score="795",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl6845.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6911",
      hide_score="27",
      revive_num="0",
      match_model="naming_qys",
      rank=51,
    },
    {
      player_name="Summer念",
      score="760",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl6310.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6838",
      hide_score="23",
      revive_num="0",
      match_model="naming_qys",
      rank=52,
    },
    {
      player_name="慢热",
      score="500",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_643.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6823",
      hide_score="32",
      revive_num="0",
      match_model="naming_qys",
      rank=53,
    },
    {
      player_name="当歌纵马",
      score="258",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_4655.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_7003",
      hide_score="40",
      revive_num="0",
      match_model="naming_qys",
      rank=54,
    },
    {
      player_name="龙霸天下",
      score="54",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_1856.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6791",
      hide_score="25",
      revive_num="0",
      match_model="naming_qys",
      rank=55,
    },
    {
      player_name="黄艳",
      score="-66",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/GtpTnF0xx2aCicuDotJWfxia6BF7DMFX9OzqJxD6zFkRavo32tYZaCIIGBdv6UySvBxE4O5F9Q7kzhC7nyX5XSVQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102110050",
      hide_score="35",
      revive_num="0",
      match_model="naming_qys",
      rank=56,
    },
    {
      player_name="記憶de承渃",
      score="-114",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl6394.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6860",
      hide_score="32",
      revive_num="0",
      match_model="naming_qys",
      rank=57,
    },
    {
      player_name="Fender丶",
      score="-648",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl2003.JPG",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_7001",
      hide_score="38",
      revive_num="0",
      match_model="naming_qys",
      rank=58,
    },
    {
      player_name="揪揪",
      score="-2533",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/FzalLtTCjEABejdiaZzBXo3exbZthmVBgiafy0O6kUReJoPPwumjibiaibAQR34nZLpgra46zxBOxyqEt37wHfL6O5w/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102823245",
      hide_score="21",
      revive_num="0",
      match_model="naming_qys",
      rank=59,
    },
    {
      player_name="只愿珍惜",
      score="-6081",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_7903.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6981",
      hide_score="24",
      revive_num="0",
      match_model="naming_qys",
      rank=60,
    },
    {
      player_name="🐳",
      score="859",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/INc61dATFS9lXrI4lUJglPMDzqOSqpYkOQETU0agMVFHzIqOTLGdpc1YichxzOv2RNsY7IcIQtcgj4wAYwoB3PQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102843179",
      hide_score="25",
      revive_num="0",
      match_model="naming_qys",
      rank=61,
    },
    {
      player_name="娜娜",
      score="830",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl2032.JPG",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6855",
      hide_score="28",
      revive_num="0",
      match_model="naming_qys",
      rank=62,
    },
    {
      player_name="荟夷^O^",
      score="776",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/JOJsc51TIjzu9cEib4a3dcfu0tmQpR2bM4iciafCKauvvWDzRr8OuXFTs0clvNDAXL1SIDRfM6JR8ko5yJOxVkXww/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="10813096",
      hide_score="14",
      revive_num="0",
      match_model="naming_qys",
      rank=63,
    },
    {
      player_name="老子最强",
      score="721",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/iazUfYZQYBny44fCHM1hwniazMjh6oSpUslQibQqLBJicVjl3cd8Kx9pnictkhVKtGh5ickxsib7XtvY4sgj95AJ3ncrQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102813899",
      hide_score="18",
      revive_num="0",
      match_model="naming_qys",
      rank=64,
    },
    {
      player_name="哥与传奇",
      score="719",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/PYPcl9BcsojetlMCnbtFdfZYoBprn3jMeWIEoHibrtt62wj0ib1aqiaAkU9dGpqpic9PDlXz0TSN60nf41OmzQT36g/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102424460",
      hide_score="31",
      revive_num="0",
      match_model="naming_qys",
      rank=65,
    },
    {
      player_name="℡青涩&",
      score="711",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTIGMrrjGucicupSFV7uMaRmgiakkDbcxPX3VsCOdHbjMbd2lUucXT14PtqOLpWNTeQnZbzPle1hpvxQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102586302",
      hide_score="27",
      revive_num="0",
      match_model="naming_qys",
      rank=66,
    },
    {
      player_name="年少猖狂必成皇",
      score="636",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_1915.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6940",
      hide_score="23",
      revive_num="0",
      match_model="naming_qys",
      rank=67,
    },
    {
      player_name="浮华",
      score="548",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_3127.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6925",
      hide_score="20",
      revive_num="0",
      match_model="naming_qys",
      rank=68,
    },
    {
      player_name="天下无不散之筵席",
      score="379",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_498.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6962",
      hide_score="27",
      revive_num="0",
      match_model="naming_qys",
      rank=69,
    },
    {
      player_name="一剑钟青",
      score="361",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTIgZ8Vda7Gn59x2s79Gk2u3kWGIjEhE2AXjcnnCgJhX3PAXLrOJ8m1ZhACXvVNHwVm0DHcKTEhCBw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102874679",
      hide_score="22",
      revive_num="0",
      match_model="naming_qys",
      rank=70,
    },
    {
      player_name="子墨鱼🐟",
      score="229",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83erbEmOX3L6GavTkG2qmO6j8W72PoricuJgcId8pTz02rvqpIhXCn4erypw1UpgH4VtNvL16QTzXLGg/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="101684545",
      hide_score="32",
      revive_num="1",
      match_model="naming_qys",
      rank=71,
    },
    {
      player_name="范医生",
      score="228",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/qeF6XO8zjK3hzo48J7xCMKuLPA4YL3LfCUZicmy35aQ4iccEIFgibV2dWZpzEedNvpLK0hNLv4Xdgn3ibeNALmVW7A/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102759012",
      hide_score="25",
      revive_num="0",
      match_model="naming_qys",
      rank=72,
    },
    {
      player_name="PHJ",
      score="221",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/KcZ8S5Q2Qs9l3U4JrAbA5CPIUU7TPVZlkI2LdR6ic0cZlpgeqQdpRnjhkgMAuJiciaJKPiacCVk5kRXQaofSubdRvQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102807198",
      hide_score="17",
      revive_num="0",
      match_model="naming_qys",
      rank=73,
    },
    {
      player_name="绵绵",
      score="216",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/l4DSdfI0GaEib84dVdsvjLF6jg07AKTJ9kgicqKhWtofTym70VzgQ28nerHgItQsWxr9dbdFO1A5sN4v04jicoHRQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="101068951",
      hide_score="16",
      revive_num="0",
      match_model="naming_qys",
      rank=74,
    },
    {
      player_name="鱼传尺愫",
      score="90",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl1296.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6825",
      hide_score="28",
      revive_num="0",
      match_model="naming_qys",
      rank=75,
    },
    {
      player_name="君子兰",
      score="83",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/eZkDFRFLrOroGTqNFMpcbDRZJUmWOLIQzhZfmnkleqnrvLCSghviaAJ9Y1gfnPGrZJfL05lzqgScK04ibFIcbfiaw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102863905",
      hide_score="31",
      revive_num="0",
      match_model="naming_qys",
      rank=76,
    },
    {
      player_name="几度失手",
      score="-90",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_139.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6993",
      hide_score="15",
      revive_num="0",
      match_model="naming_qys",
      rank=77,
    },
    {
      player_name="良人书生",
      score="-91",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/8zIufByAH46DeNibQic8Jic1y3BDWC3HAZicyFWVBUmrt7Ec3JkBDzNDAicbomnDWXhxcr9lztTpGiayMeOFylMIRb8A/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102875235",
      hide_score="14",
      revive_num="0",
      match_model="naming_qys",
      rank=78,
    },
    {
      player_name="喜欢",
      score="-100",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl3104.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6832",
      hide_score="13",
      revive_num="0",
      match_model="naming_qys",
      rank=79,
    },
    {
      player_name="年少如风",
      score="-136",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_6647.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6937",
      hide_score="22",
      revive_num="0",
      match_model="naming_qys",
      rank=80,
    },
    {
      player_name="烈酒烫心",
      score="-142",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_6912.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6831",
      hide_score="25",
      revive_num="0",
      match_model="naming_qys",
      rank=81,
    },
    {
      player_name="温度1号",
      score="-267",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/kpzkw31Vc6gLO0mxicN9KdDpIEYqmibl9Gzfr3Q3m8wia0I9flGTia7odd3FkwEQyqSaxGXWNxia3InuoJpichicaRSPg/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102892196",
      hide_score="36",
      revive_num="0",
      match_model="naming_qys",
      rank=82,
    },
    {
      player_name="咬遍天下无敌手",
      score="-381",
      head_link="http://jydown.jyhd919.cn/head_images3/girl/girl_girl1231.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_0_6915",
      hide_score="14",
      revive_num="0",
      match_model="naming_qys",
      rank=83,
    },
    {
      player_name="楠哥",
      score="-423",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/LKqHg3h6ouCW8Bp9HRiajCoA6ruRQsSNrkpTVBfjRjk7lhY3Fnuf0g212uBlV8UsRQz5wOy2sgaLUzPV7JDgukQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102764116",
      hide_score="31",
      revive_num="0",
      match_model="naming_qys",
      rank=84,
    },
    {
      player_name="不是你江戈",
      score="-433",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_723.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6761",
      hide_score="22",
      revive_num="0",
      match_model="naming_qys",
      rank=85,
    },
    {
      player_name="开心开心",
      score="-436",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DvxbANWkM6K1icK1O3ib9uAZBjtTKzf8q1QEI7MNhzEAzFRxYTgtdibgARWryqOBqI24iaqibibaoUpxEY6OIgc54KIg/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102858537",
      hide_score="26",
      revive_num="0",
      match_model="naming_qys",
      rank=86,
    },
    {
      player_name="熙萘^断肠人",
      score="-440",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/ERVuBcwXNr0PKNVllgMRodFbradib9HmOk3qDaXZIpiarRjLSRkPia6GO9Po7UfxmCDDn58aOe8xbUEAeZ77hDVew/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102900747",
      hide_score="25",
      revive_num="0",
      match_model="naming_qys",
      rank=87,
    },
    {
      player_name="雪梅",
      score="-442",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJanxsicaUg7qRGiaFn9KKX72icMuzUeySHW9l3J1xX1ZvtI2QZRySwoGYib7SrNbc9noYQhPdRml4YKA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102733795",
      hide_score="15",
      revive_num="2",
      match_model="naming_qys",
      rank=88,
    },
    {
      player_name="雨过天晴",
      score="-565",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLnPs1DUNIIhY03FZXDJpGZ6cnPdIG1WVW2m3QibOAO3AeEl3C9KWgN8CaPUDm2GZXTKVI7QlVf9dw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102842112",
      hide_score="27",
      revive_num="0",
      match_model="naming_qys",
      rank=89,
    },
    {
      player_name=":",
      score="-647",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/y9KuUt8q4Rs1YqOFRw0O2A1DvT05Lg1FuHQMNeBUEWvKYgUddttz80IjZE6ZJGHPJBsSat2WsfL4WrFjZU2UYA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102464149",
      hide_score="29",
      revive_num="0",
      match_model="naming_qys",
      rank=90,
    },
    {
      player_name="zcc",
      score="-664",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/2m49Z7YV3PGMA15rXTubLicxlRERtl04kM7C8pfpfsS8FpicJrFZiaPJh8UG0p1Pgc70p3NI91SySIdfzax2iauKOQ/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102635185",
      hide_score="24",
      revive_num="0",
      match_model="naming_qys",
      rank=91,
    },
    {
      player_name="晨曦尘埃",
      score="-673",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/NBYc6gBA4gaIIWXOoL4xGoMGTIG0zkwiaLnq4uQ6bGQwRXcp2mc5INAnwVHtnM8ZQP3p7QttoOJUC4x5t7mMNhA/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102826612",
      hide_score="37",
      revive_num="0",
      match_model="naming_qys",
      rank=92,
    },
    {
      player_name="我心畅享",
      score="-693",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eo9633nSCKK8xm4woctIXib7nHibaAibe29DcwVKkgU1Qbzg4awSzMnMO7jyuW087kFiaonwPcVO3Ficyw/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102732039",
      hide_score="20",
      revive_num="1",
      match_model="naming_qys",
      rank=93,
    },
    {
      player_name="开心就好",
      score="-697",
      head_link="http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83erGH4RsFibNmHRRWdd8MNWCCibk9VJcUOtYQ3zdmpR4SZaIYgrr67JgfiaVq0qRpC7yLBVTUXepmx4eg/132",
      match_name="鲸鱼千元赛第 66 期",
      player_id="102882370",
      hide_score="33",
      revive_num="0",
      match_model="naming_qys",
      rank=94,
    },
    {
      player_name="学会拥抱自己",
      score="-1428",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_482.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6876",
      hide_score="16",
      revive_num="0",
      match_model="naming_qys",
      rank=95,
    },
    {
      player_name="祭念",
      score="-3798",
      head_link="http://jydown.jyhd919.cn/head_images3/boy/boy_430.jpg",
      match_name="鲸鱼千元赛第 66 期",
      player_id="robot_tg7_1_6960",
      hide_score="7",
      revive_num="0",
      match_model="naming_qys",
      rank=96,
    },
}


--查询比赛总排行
function CMD.query_all_rank()

  return {result=0,rank_list=rank_list_test}

end

return function()

	return " query_all_rank fix ok "
end